Select
    Id,
    karteID__c,
    nn咳がす,
    Douki__c,
    Kenen__c,
    SenzaiNeeds__c,
    RoadMap__c,
    Milestone__c,
    KibousougakuyosanSuushiki__c,
    ChiikiEnsenEkimeiSuushiki__c,
    ChiikiEnsenEkimeiRiyuuSuushiki__c,
    ChumonJutakuRiyuuSuushiki__c,
    NyuukyoJikiSuushiki__c,
    NyuukyoJikiRiyuuSuushiki__c,
    KariireKenenRiyuu__c
FROM
    karte__c
WHERE
    IsDeleted = False
